name: Gosec Security Scan

on:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"

jobs:
  gosec-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18.x'
          check-latest: true
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec (root)
        working-directory: .
        run: |
          gosec -exclude-dir=arangodb -exclude-dir=badger -exclude-dir=couchbase -exclude-dir=dynamodb -exclude-dir=etcd -exclude-dir=memcache -exclude-dir=memory -exclude-dir=mongodb -exclude-dir=mysql -exclude-dir=postgres -exclude-dir=redis -exclude-dir=ristretto -exclude-dir=sqlite3 -exclude-dir=s3 -exclude-dir=bbolt -exclude-dir=azureblob -exclude-dir=mssql -exclude-dir=pebble ./....
        # -----
      - name: Run Gosec (arangodb)
        working-directory: ./arangodb
        run: gosec ./...
        # -----
      - name: Run Gosec (badger)
        working-directory: ./badger
        run: gosec ./...
        # -----
      - name: Run Gosec (couchbase)
        working-directory: ./couchbase
        run: gosec ./...
        # -----
      - name: Run Gosec (coherence)
        working-directory: ./coherence
        run: gosec ./...
        # -----
      - name: Run Gosec (dynamodb)
        working-directory: ./dynamodb
        run: gosec ./...
        # -----
      - name: Run Gosec (etcd)
        working-directory: ./etcd
        run: gosec ./...
        # -----
      - name: Run Gosec (memcache)
        working-directory: ./memcache
        run: gosec ./...
        # -----
      - name: Run Gosec (memory)
        working-directory: ./memory
        run: gosec ./...
        # -----
      - name: Run Gosec (mongodb)
        working-directory: ./mongodb
        run: gosec ./...
        # -----
      - name: Run Gosec (mysql)
        working-directory: ./mysql
        run: gosec ./...
        # -----
      - name: Run Gosec (postgres)
        working-directory: ./postgres
        run: gosec ./...
        # -----
      - name: Run Gosec (redis)
        working-directory: ./redis
        run: gosec ./...
        # -----
      - name: Run Gosec (sqlite3)
        working-directory: ./sqlite3
        run: gosec ./...
        # -----
      - name: Run Gosec (s3)
        working-directory: ./s3
        run: gosec ./...
        # -----
      - name: Run Gosec (ristretto)
        working-directory: ./ristretto
        run: gosec ./...
        # -----
      - name: Run Gosec (bbolt)
        working-directory: ./bbolt
        run: gosec ./...
        # -----
      - name: Run Gosec (azureblob)
        working-directory: ./azureblob
        run: gosec ./...
        # -----
      - name: Run Gosec (mssql)
        working-directory: ./mssql
        run: gosec ./...
        # -----
      - name: Run Gosec (pebble)
        working-directory: ./pebble
        run: gosec ./...
        # -----
