name: Release Drafter S3
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 's3/**'
jobs:
    draft_release_s3:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v6
                with:
                    config-name: release-drafter-s3.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
